module.exports={
    user: require('./userController'),
    posts: require('./postController'),
    auth: require('./authController'),
    hero: require('./heroController'),
    monster: require('./monsterController'),
    party: require('./partyController'),
    session: require('./sessionController'),
    encounter: require('./encounterController'),
    classes: require('./classController'),
    weapon: require('./weaponController'),
    spell: require('./spellController'),
    race: require('./raceController'),
    equipment: require('./equipmentController'),
    auth: require('./authController'),
    }